### ISSUE TITLE
Are backports planned?

### ISSUE THREAD

**Issue by FR00TP3NCH** [ABU008/Legacy-Bob#3]
I was wondering if you could backport this to 1.20 - 1.20.6 if you could.

**Comment by ABU008** [comment]
I'll try and back port it to 1.20 - 1.20.6. but since the java versions are different between 1.20 - 1.20.6 it may take some time.

**Comment by ABU008** [comment]
i backported the mod down to 1.20.6, would've taken too long to backport it all the way down to 1.20 because of the huge difference in java version

**Comment by FR00TP3NCH** [comment]
alr

**Comment by FR00TP3NCH** [comment]
if you do backport it to older versions it would do wonders for people trying to remake the legacy console versions like the 360 edition but im not trying to pressure you into doing it

**Comment by ABU008** [comment]
there is already a mod that remakes legacy console edition, it's called Legacy4J. here is the link: https://modrinth.com/mod/legacy4j

**Comment by FR00TP3NCH** [comment]
i use that a lot but thanks

**Comment by FR00TP3NCH** [comment]
the bob/sway in this mod MIGHT be a tiny more accurate but ill use l4j til you backport this mod which the chances of that are slim

**Comment by ABU008** [comment]
I will eventually back port it, but going to Minecraft version that doesn't even use the same java version as 1.21.1 it will take a while.

**Comment by FR00TP3NCH** [comment]
righto
